home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name= 'home'

urlpatterns = [
    path('',views.index,name='index'),
]



urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'register'

urlpatterns = [
    path('signup/', views.signup, name ='signup'),
    path('login/', views.loginuser, name ='login'),
    path('logout/', views.logoutuser, name='logout')
]



urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

saleProduct/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    #home
    path('',include('home.urls')),
    #user
    path('',include('appUser.urls')),
    #register
    path('',include('register.urls')),
    #product
    path('',include('appProduct.urls')),
    #auth
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='user/change-password.html',
            success_url = '/'
        ),
        name='change_password'
    ),
    #order
    path('', include('order.urls')),
    #favourite
    path('', include('favourite.urls')),
    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
            template_name='user/password-reset/password_reset.html',
            subject_template_name='user/password-reset/password_reset_subject.txt',
            email_template_name='user/password-reset/password_reset_email.html',
            # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
            template_name='user/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
            template_name='user/password-reset/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name='user/password-reset/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/user/password-reset/password_reset.html
{% extends "base/base.html" %}
{% block block_body_not_nav %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-md">
      <a class="navbar-brand" href="{% url 'home:index' %}">Uniqlo</a>
    </div>
</nav>


<h1 class="text-center mb-4 display-3" style="margin-top: 110px;">Reset Password</h1>

{% if error %}
  <div class="alert alert-warning" role="alert">
    <span>{{ error }}</span> 
</div>
{% endif %}
<form action="" method="POST" class="d-flex flex-column align-items-center">
  {% csrf_token %}
  <div class="mb-3 w-50">
    <label for="id_email" class="form-label">Email</label>
    <input type="email" name="email" autofocus="" required="" id="id_email" class="form-control" aria-describedby="emailHelp">
  </div>
  <button type="submit" class="btn btn-outline-dark mt-2">Send Email</button>
</form>
   
{% endblock block_body_not_nav%}

templates/user/password-reset/password_reset_complete.html
{% extends "base/base.html" %}
{% block block_body_not_nav %}
<h2 class="text-center mt-5 mb-4 display-2">Reset Password</h2>
<h3 class="text-center mt-5 mb-4 display-5">Your password has been changed.</h3>
<div class="w-100 text-center mt-5">
    <a href="{% url 'register:login' %}"  class="btn btn-outline-secondary">Click here to Login</a>
</div>
{% endblock block_body_not_nav%}

templates/user/password-reset/password_reset_confirm.html
{% extends "base/base.html" %}
{% block block_body %}


<h1 class="text-center mt-5 mb-4 display-3">Change Password</h1>

{% if error %}
  <div class="alert alert-warning" role="alert">
    <span>{{ error }}</span> 
</div>
{% endif %}
<form action="" method="POST" class="d-flex flex-column align-items-center" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3 w-50">
    <label for="id_password" class="form-label">Password</label>
    <input type="password"  name="new_password1" required="" id="id_new_password1" class="form-control">
  </div>
  <div class="mb-3 w-50">
    <label for="id_password" class="form-label">Password</label>
    <input type="password"  name="new_password2" required="" id="id_new_password2" class="form-control">
  </div>
  <button type="submit" class="btn btn-primary">Change password</button>
</form>
   
{% endblock %}

templates/user/password-reset/password_reset_done.html
{% extends "base/base.html" %}
{% block block_body_not_nav %}

<h1 class="text-center mt-5 mb-4 display-2">Reset Password</h1>
<p class="text-center mb-4">We have sended you reset password link on your email. Please Check Your Email.</p>
<div class="w-100 text-center mt-5">
    <a href="{% url 'home:index' %}" class="btn btn-outline-secondary">Back Home</a>
</div>

{% endblock block_body_not_nav%}

templates/user/password-reset/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Hey, You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

templates/user/password-reset/password_reset_form.html
<h2>Reset Password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
</form>