home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name= 'home'

urlpatterns = [
    path('',views.index,name='index'),
]



urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'register'

urlpatterns = [
    path('signup/', views.signup, name ='signup'),
    path('login/', views.loginuser, name ='login'),
    path('logout/', views.logoutuser, name='logout')
]



urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

saleProduct/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    #home
    path('',include('home.urls')),
    #user
    path('',include('appUser.urls')),
    #register
    path('',include('register.urls')),
    #product
    path('',include('appProduct.urls')),
    #auth
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='user/change-password.html',
            success_url = '/'
        ),
        name='change_password'
    ),
    #order
    path('', include('order.urls')),
    #favourite
    path('', include('favourite.urls')),
    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
            template_name='user/password-reset/password_reset.html',
            subject_template_name='user/password-reset/password_reset_subject.txt',
            email_template_name='user/password-reset/password_reset_email.html',
            # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
            template_name='user/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
            template_name='user/password-reset/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name='user/password-reset/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

register/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #mối quan hệ một một
    #additional
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)    
    birth_date = models.DateField(help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    site = models.URLField(blank=True) #blank=true có nghĩa là để trống không cần điền vẫn ok
    avatar = models.ImageField(upload_to='images', blank=True) 
    address = models.CharField(max_length=200, default=None, blank=True, null=True)
    phonenumber = models.CharField(max_length=20, default=None, blank=True, null=True)
    def __str__(self) -> str:
        return self.user.username
    

register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.fields import DateField
from .models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    password1 = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password','password1')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfile
        fields= ('first_name','last_name','birth_date','site', 'avatar')
        

register/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import UserProfileForm , UserForm
from django.contrib.auth.decorators import login_required,user_passes_test
from order.models import Cart
from order.views import carts
from favourite.views import favourites
from appProduct.models import Product
from django.contrib import messages


@user_passes_test(lambda u: u.is_anonymous, login_url='home:index')
def signup(request):
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        if request.POST['password']==request.POST['password1']:
            if user_form.is_valid() and profile_form.is_valid():
                user= user_form.save() 
                user.set_password(user.password) 
                user.save()
                profile= profile_form.save(commit=False)
                profile.user = user
                if 'avatar' in request.FILES:
                    profile.avatar = request.FILES['avatar']
                profile.save()
                login(request, user)
                return redirect('home:index')
            else:
                return render(request, 'register/signup.html', {'user_form': user_form, 'profile_form': profile_form, 'error': "Wrong fomat"})
        else:
            return render(request, 'register/signup.html', {'user_form': user_form, 'profile_form': profile_form, 'error': "Password Wrong"})
    else:
        user_form = UserForm()
        profile_form= UserProfileForm()
    return render(request, 'register/signup.html', {'user_form': user_form, 'profile_form': profile_form})

@user_passes_test(lambda u: u.is_anonymous, login_url='home:index')
def loginuser(request):
    favourites.clear()
    request.session['favourites']=favourites
    if request.method == "GET":
        return render(request, 'register/login.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'],password=request.POST['password'])
        if user is None:
            return render(request, 'register/login.html', {'form': AuthenticationForm(), 'error': "username or password wrong"})
        else: 
            login(request, user) 
            
            #nếu như có session thì thêm vào cart
            try:
                cartInfo = request.session['carts']
            except:
                cartInfo = None
            if cartInfo != None:
                for key, value in cartInfo.items():
                    try:
                        productDetail = Product.objects.filter(name = value['name'], price = value['price'])[0]
                    except Product.DoesNotExist:
                        productDetail = None
                    try:
                        cartItem = Cart.objects.get(product = productDetail,user = request.user, color = value['color'], size = value['size'])
                        # cartItem = Cart.objects.get(product = productDetail,user = user)
                    except Cart.DoesNotExist:
                        cartItem = None
                    if cartItem != None:
                        cartItem.quantity = int(value['num'])
                        cartItem.save()
                    else:
                        newCartItem = Cart(user = request.user, product = productDetail,quantity = int(value['num']), color = value['color'], size = value['size']) 
                        newCartItem.save()
                        
                #cập nhật cart vào session user
                quantity=0
                listCart = Cart.objects.filter(user = user)
                for item in listCart:
                    quantity += int(item.quantity)
                request.session['quantity']=quantity   
            return redirect('home:index')
        
@login_required
def logoutuser(request):
    carts.clear()
    favourites.clear()
    try:
        for key in list(request.session.keys()):
            del request.session[key]
    except KeyError:
        pass
    if request.session.test_cookie_worked():
        request.session.delete_test_cookie()
    else:
        request.session.set_test_cookie()
    if request.method=="POST":
        logout(request)
        return redirect('home:index')
    

templates/register/login.html
{% extends "base/base.html" %}
{% block block_body_not_nav %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-md">
    <a class="navbar-brand" href="{% url 'home:index' %}">Uniqlo</a>
  </div>
</nav>


<h1 class="text-center mt-5 mb-4 display-3">Login</h1>

{% if error %}
  <div class="mb-3 mt-5 w-100 d-flex justify-content-center align-items-center" role="alert" >
    <div class="w-50 alert alert-secondary">{{ error }}</div> 
  </div>
{% endif %}
<form action="" method="POST" class="d-flex flex-column align-items-center">
  {% csrf_token %}
  <div class="mb-3 w-50">
    <label for="id_username" class="form-label">Username</label>
    <input type="text" name="username" autofocus="" required="" id="id_username" class="form-control" aria-describedby="emailHelp">
  </div>
  <div class="mb-3 w-50">
    <label for="id_password" class="form-label">Password</label>
    <input type="password" name="password" required="" id="id_password" class="form-control">
  </div>
  <a href="{% url 'register:signup' %}" class="mb-3" style="text-decoration: none; color: #212529; font-size: 16px ">Signup new member</a>
  <button type="submit" class="btn btn-outline-dark">login</button>
</form>
   
{% endblock block_body_not_nav %}

templates/register/signup.html
{% extends "base/base.html" %}
{% block block_body_not_nav %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-md">
    <a class="navbar-brand" href="{% url 'home:index' %}">Uniqlo</a>
  </div>
</nav>

<h1 class="text-center mt-5 mb-4 display-3">Signup</h1>

{% if error %}
  <div class="alert alert-warning" role="alert">
    <span>{{ error }}</span> 
</div>
{% endif %}
<form enctype="multipart/form-data" method="POST" class="d-flex flex-column align-items-center mb-5">
  {% csrf_token %}
  <div class="mb-3 w-50">
    <label for="id_username" class="form-label">Username</label>
    <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username" class="form-control" aria-describedby="emailHelp">
  </div>
  <div class="mb-3 w-50">
    <label for="id_email" class="form-label">Email</label>
    <input type="email" name="email" autofocus="" required="" id="id_email" class="form-control" aria-describedby="emailHelp">
  </div>
  <div class="mb-3 w-50">
    <label for="id_password" class="form-label">Password</label>
    <input type="password" name="password" required="" id="id_password" class="form-control">
  </div>
  <div class="mb-3 w-50">
    <label for="id_password1" class="form-label">Password</label>
    <input type="password" name="password1" required="" id="id_password1" class="form-control">
  </div>
  <div class="mb-3 w-50">
    <label for="id_first_name" class="form-label">First Name</label>
    <input  type="text" name="first_name" maxlength="256" required="" id="id_first_name" class="form-control" aria-describedby="emailHelp">
  </div>
  <div class="mb-3 w-50">
    <label for="id_last_name" class="form-label">Last Name</label>
    <input  type="text" name="last_name" maxlength="256" required="" id="id_last_name" class="form-control" aria-describedby="emailHelp">
  </div>
  <div class="mb-3 w-50">
    <label for="id_birth_date" class="form-label">Birth Day</label>
    <input type="text" name="birth_date" required="" id="id_birth_date" class="form-control" aria-describedby="emailHelp">
  </div>
  <div class="mb-3 w-50">
    <label for="id_site" class="form-label">Url</label>
    <input type="url" name="site" maxlength="200" id="id_site" class="form-control" aria-describedby="emailHelp">
  </div>
  <div class="mb-3 w-50">
    <label for="id_avatar" class="form-label">Default file input example</label>
    <input class="form-control"  type="file" name="avatar" accept="image/*" id="id_avatar">
  </div>
  <button type="submit" class="btn btn-outline-dark mb-5">Register</button>
</form>

{% endblock block_body_not_nav %}