home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name= 'home'

urlpatterns = [
    path('',views.index,name='index'),
]



urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name ='order'

urlpatterns = [
    path('product/addcart/', views.addcart , name ='addcart'),
    path('product/<int:product_pk>/addcart/', views.addcartdetail, name ='detailproductaddcart'),
    path('basket/addcart/', views.addcartbasket, name ='addcartbasket'),
    path('basket/', views.basket , name ="basket"),
    path('basket/<int:cart_pk>/deletecart/', views.deletecart , name ="deletecart"),
    path('checkout/', views.checkout , name ="checkout"),
    path('confirmcheckout/', views.confirmcheckout , name ="confirmcheckout"),
    path('sucesscheckout/', views.sucesscheckout , name ="sucesscheckout"),
]


# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

saleProduct/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    #home
    path('',include('home.urls')),
    #user
    path('',include('appUser.urls')),
    #register
    path('',include('register.urls')),
    #product
    path('',include('appProduct.urls')),
    #auth
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='user/change-password.html',
            success_url = '/'
        ),
        name='change_password'
    ),
    #order
    path('', include('order.urls')),
    #favourite
    path('', include('favourite.urls')),
    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
            template_name='user/password-reset/password_reset.html',
            subject_template_name='user/password-reset/password_reset_subject.txt',
            email_template_name='user/password-reset/password_reset_email.html',
            # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
            template_name='user/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
            template_name='user/password-reset/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name='user/password-reset/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

order/models.py
from django.db import models
from appProduct.models import Product, Gender, Color, Size
from django.contrib.auth.models import User


# Create your models here.

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    color = models.CharField(max_length=20,default=None, blank=True, null=True)
    size = models.CharField(max_length=20,default=None, blank=True, null=True)
    image = models.ImageField(upload_to='cartImages', default=None, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    totalprice = models.DecimalField(default=None, blank=True, null=True,max_digits = 20,decimal_places=2)
    def __str__(self) -> str:
        return self.product.name 
    
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(default="XXXXXXX", max_length=256)
    state_choices = (
        ('In Queue', 'In Queue'),
        ('Processing', 'Processing'),
        ('Ready', 'Ready'),
        ('Delivered', 'Delivered'),
        ('Paid', 'Paid'),
        ('Cancelled', 'Cancelled'),
    ) 
    state = models.CharField( max_length=256, choices=state_choices, default=state_choices[0][0])
    totalprice = models.IntegerField(default=0)
    quantity = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now=True)
    phonenumber = models.CharField(max_length=20, default=None, blank=True, null=True)
    address = models.CharField(max_length=200, default=None, blank=True, null=True)
    def __str__(self) -> str:
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        return self.totalprice
    
class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, blank=True, null=True)
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE, default=None, blank=True, null=True)
    color = models.CharField(max_length=20,default=None, blank=True, null=True)
    size = models.CharField(max_length=20,default=None, blank=True, null=True)
    quantity = models.IntegerField(default=0)
    totalprice = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return '{}'.format(self.id)
    
    def get_cost(self):
        return self.totalprice * self.quantity

order/views.py
from appProduct.views import product
from django.contrib.auth import SESSION_KEY
from django.http.response import HttpResponse,JsonResponse
from django.shortcuts import render, redirect,get_object_or_404
from .models import Order, OrderDetail, Cart
from appProduct.models import Product, Gender, Color, ImageProduct, Size, Variants
from django.contrib.auth.decorators import login_required,user_passes_test ,permission_required
from django.template.loader import render_to_string, get_template
from django.views.decorators.csrf import csrf_protect
from register.models import  UserProfile
import random



# Create your views here.

# for key, value in request.session.carts.items
#     key: value



carts = {}
def addcart(request):
    if request.is_ajax():
        id_product = request.POST.get('id')
        num = request.POST.get('num')
        productDetail = Product.objects.get(id=id_product)
        if productDetail:
            try:
                variant = Variants.objects.get(product= productDetail)
            except Variants.DoesNotExist:
                variant = None
        else:
            variant = None
        if variant:
            colorlist = variant.color.all()
            sizelist = variant.size.all()
            color = colorlist[0]
            size = sizelist[0]
            colorid = Color.objects.filter(name=color)[0].id
            sizeid = Size.objects.filter(name=size)[0].id
        else:
            color = "None+"
            size = "None+"
            sizeid=1010
            colorid=1010
        if request.user.is_authenticated:       
            if id_product in carts.keys():
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': int(carts[id_product]['num'])+1,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int((int(carts[id_product]['num'])+1) * int(productDetail.price))
                }
            else:
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': num,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(productDetail.price))
                }
        else:
            if str(id_product)+str(colorid)+str(sizeid) in carts.keys():
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': int(carts[str(id_product)+str(colorid)+str(sizeid)]['num'])+1,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int((int(carts[str(id_product)+str(colorid)+str(sizeid)]['num'])+1) * int(productDetail.price))
                }
            else:
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': num,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(productDetail.price))
                }
        if request.user.is_authenticated:
            carts[id_product]= itemCart
        else:
            carts[str(id_product)+str(colorid)+str(sizeid)]=itemCart
        request.session['carts'] = carts
        cartInfo = request.session['carts']
        if request.user.is_authenticated:
            try:
                cartItem = Cart.objects.get(product = productDetail,user = request.user, color = itemCart['color'], size = itemCart['size'])
            except Cart.DoesNotExist:
                cartItem = None
            if cartItem != None:
                cartItem.quantity = int(itemCart['num'])
                cartItem.save()
            else:
                newCartItem = Cart(user = request.user, product = productDetail,quantity = int(itemCart['num']), color = itemCart['color'], size = itemCart['size'], image=itemCart['image'])
                newCartItem.save()
            quantity=0
            totalprice=0
            listCart = Cart.objects.filter(user = request.user)
            for item in listCart:
                quantity += int(item.quantity)
                totalprice += int(item.quantity) * int(item.product.price)
            request.session['quantity']=quantity
            print(totalprice)
        else:
            quantity=0
            totalprice=0
            for key, value in cartInfo.items():
                quantity += int(value['num'])
                totalprice += int(value['num'])*int(float(value['price']))
            request.session['quantity']=quantity
        # html = render_to_string('product/addcart.html',{'carts': cartInfo})
    return JsonResponse({'quantity': quantity, 'quantitproduct': itemCart['num'], 'carts': request.session['carts'], 'totalprice': totalprice})

def addcartdetail(request, product_pk):
    if request.is_ajax():
        id_product = request.POST.get('id')
        num = request.POST.get('num')
        colorid = request.POST.get('color')
        sizeid = request.POST.get('size')
        if colorid:
            color = Color.objects.get(id=colorid)
        else: 
            color = "None+"
            colorid=1010
        if sizeid:
            size = Size.objects.get(id=sizeid)
        else:
            size = "None+"
            sizeid=1010
        if num:
            num=num
        else:
            num=1
        productDetail = Product.objects.get(id=id_product)
        if productDetail:
            try:
                variant = Variants.objects.get(product= productDetail)
            except Variants.DoesNotExist:
                variant = None
        else:
            variant = None
        if request.user.is_authenticated:
            if id_product in carts.keys():
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,   #nếu có hình ảnh thì convert sang string
                    'num': int(carts[id_product]['num']) + int(num),
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(float(productDetail.price)))
                }
            else:
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': num,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(float(productDetail.price)))
                }
        else:
            if str(id_product)+str(colorid)+str(sizeid) in carts.keys():
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,   #nếu có hình ảnh thì convert sang string
                    'num': int(carts[str(id_product)+str(colorid)+str(sizeid)]['num']) + int(num),
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(float(productDetail.price)))
                }
            else:
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': num,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(float(productDetail.price)))
                }
        if request.user.is_authenticated:
            carts[id_product]= itemCart
        else:
            carts[str(id_product)+str(colorid)+str(sizeid)]=itemCart
        request.session['carts'] = carts
        cartInfo = request.session['carts']
        if request.user.is_authenticated:
            try:
                cartItem = Cart.objects.get(product = productDetail,user = request.user, color = itemCart['color'], size = itemCart['size'])
            except Cart.DoesNotExist:
                cartItem = None
            if cartItem != None:
                cartItem.quantity = int(itemCart['num'])
                cartItem.totalprice = int(itemCart['num'])*productDetail.price
                cartItem.save()
            else:
                newCartItem = Cart(user = request.user, product = productDetail,quantity = int(itemCart['num']), totalprice = int(itemCart['num'])*productDetail.price, color = itemCart['color'], size = itemCart['size']) 
                newCartItem.save()
            quantity=0
            totalprice=0
            listCart = Cart.objects.filter(user = request.user)
            for item in listCart:
                quantity += int(item.quantity)

templates/order/addcart.html
{{carts}}

templates/order/checkout.html
{% extends "base/base.html" %} {% block block_body %} {% load static %}

<div style="padding-top: 85px;">
</div>

<div class="container">
    <div class="banner__select">
        <nav class="banner__nav">
            <ol class="banner__nav--group">
                <li class="banner__nav--item">
                    <a href="{% url 'home:index' %}" class="banner__nav--link" style="color: #212529;">
                        <span class="banner__nav--span label--primary">
                            HOME
                        </span>
                    </a>
                </li>
                <li class="banner__nav--item">
                    <a href="{% url 'order:basket' %}" class="banner__nav--link" style="color: #212529;">
                        <span class="banner__nav--span label--primary">
                            Basket
                        </span>
                    </a>
                </li>
                <li class="banner__nav--item active">
                    <span class="banner__nav--span label--primary">
                        Checkout
                    </span>
                </li>
            </ol>
        </nav>
    </div>
</div>


<section class="container" style="margin-bottom: 3.125rem;">
    <div class="product__header" style="margin-bottom: 1rem;">
        <h1 class="product__header--h1">
            Checkout
        </h1>
    </div>
    <p style="font-weight: 300; font-size:1.4rem; color:#1b1b1b ">
        Giao hàng miễn phí cho các giao dịch mua trên 3.000 yên. Miễn phí vận chuyển nếu bạn nhận nó tại cửa hàng.
    </p>
</section>

<div class="container">
    <div class="row justify-content-center">
        <div class="col col-7" style="padding: 3.25rem 0">
            <div class="basket__bill">
                <div class="basket__bill--container">
                    <div class="basket__bill--details">
                        <div class="basket__bill--header">
                            <span class="basket__bill--span" style="margin-right: auto;">
                                <font style="vertical-align: inherit;">
                                    <font style="vertical-align: inherit;">Chi tiết đơn hàng</font>
                                </font>
                            </span>
                            <span class="basket__bill--span">
                                <font style="vertical-align: inherit;">
                                    <font style="vertical-align: inherit;" id="listCartQuantity">{{cartlist|length}} </font>
                                </font>
                                <font style="vertical-align: inherit;">
                                    <font style="vertical-align: inherit;">trường hợp</font>
                                </font>
                            </span>
                        </div>
                        <hr class="basket__bill--border--bottom">
                        <div class="basket__bill--info">
                            <table class="basket__bill--table">
                                <tbody>
                                    <tr>
                                        <td class="basket__bill--td--start">
                                            <span class="basket__bill--td--span">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tổng sản phẩm</font></font>
                                            </span>
                                        </td>
                                        <td class="basket__bill--td--end">
                                            <span class="basket__bill--td--span">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;" id="totalquantity">{{quantity}}</font></font>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="basket__bill--td--start">
                                            <span class="basket__bill--td--span">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Trạng thái</font></font>
                                            </span>
                                        </td>
                                        <td class="basket__bill--td--end">
                                            <span class="basket__bill--td--span">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Chưa quyết định</font></font>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="basket__bill--td--start">
                                            <span class="basket__bill--td--span basket__bill--td--span--weight">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tổng Phụ</font></font>
                                            </span>
                                        </td>
                                        <td class="basket__bill--td--end">
                                            <span class="basket__bill--td--span basket__bill--td--span--weight">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">¥ </font></font>
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;" id="totalpricecart">{{totalprice}}</font></font>
                                            </span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="basket__bill--td--start">
                                            <span class="basket__bill--td--span">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Thuế tiêu dùng</font></font>
                                            </span>
                                        </td>
                                        <td class="basket__bill--td--end">
                                            <span class="basket__bill--td--span">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">¥ 2000</font></font>
                                            </span>
                                        </td>
                                    </tr>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td class="basket__bill--td--start">
                                            <span class="basket__bill--td--span basket__bill--td--span--weight">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tổng (đã bao gồm thuê)</font></font>
                                            </span>
                                        </td>
                                        <td class="basket__bill--td--end">
                                            <span class="basket__bill--td--span basket__bill--td--span--weight">
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">¥ </font></font>
                                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;" id="totalpricecarttax">{{totalprice|add:2000}}</font></font>
                                            </span>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="product__details--button" id="deleteCartCheckout">
                    <a class="button--secondary button--primary--red" href="{% url 'order:confirmcheckout' %}" id="disabledCartCheckout">
                        <p class="button--secondary--label">
                            <font style="vertical-align: inherit;">
                                <font style="vertical-align: inherit;">xác nhận thanh toán</font>
                            </font>
                        </p>
                    </a>
                    <p style=" height: 1rem; "></p>
                </div>
                <a href="{% url 'order:basket' %}" class="button--secondary button--secondary--light">
                    <p class="button--secondary--label">
                        <font style="vertical-align: inherit;">
                            <font style="vertical-align: inherit;">BACK CART</font>
                        </font>
                    </p>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- 
<h1>Vui Lòng xác nhận</h1>
<a href="{% url 'order:confirmcheckout' %}">confirm</a> -->

{% endblock %}

templates/order/sucesscheckout.html
{% extends "base/base.html" %} {% block block_body %} {% load static %}

<div style="padding-top: 85px;">
</div>
<div class="container text-center w-100" style="padding-top:15rem">
    <h1 style="font-weight: 300; height:70vh ;font-size:5rem; color:#1b1b1b;">Thanh toán thành công</h1>
</div>

{% endblock %}