appUser/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'appUser'

urlpatterns = [
    path('userInfo/', views.userInfo, name ='userInfo'),
    path('editInfo/', views.editInfo, name ='editInfo'),
    path('order/', views.orderUser, name ='order'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name= 'home'

urlpatterns = [
    path('',views.index,name='index'),
]



urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name ='order'

urlpatterns = [
    path('product/addcart/', views.addcart , name ='addcart'),
    path('product/<int:product_pk>/addcart/', views.addcartdetail, name ='detailproductaddcart'),
    path('basket/addcart/', views.addcartbasket, name ='addcartbasket'),
    path('basket/', views.basket , name ="basket"),
    path('basket/<int:cart_pk>/deletecart/', views.deletecart , name ="deletecart"),
    path('checkout/', views.checkout , name ="checkout"),
    path('confirmcheckout/', views.confirmcheckout , name ="confirmcheckout"),
    path('sucesscheckout/', views.sucesscheckout , name ="sucesscheckout"),
]


# urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

saleProduct/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    #home
    path('',include('home.urls')),
    #user
    path('',include('appUser.urls')),
    #register
    path('',include('register.urls')),
    #product
    path('',include('appProduct.urls')),
    #auth
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='user/change-password.html',
            success_url = '/'
        ),
        name='change_password'
    ),
    #order
    path('', include('order.urls')),
    #favourite
    path('', include('favourite.urls')),
    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
            template_name='user/password-reset/password_reset.html',
            subject_template_name='user/password-reset/password_reset_subject.txt',
            email_template_name='user/password-reset/password_reset_email.html',
            # success_url='/login/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
            template_name='user/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
            template_name='user/password-reset/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name='user/password-reset/password_reset_complete.html'
        ),
        name='password_reset_complete'),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

order/models.py
from django.db import models
from appProduct.models import Product, Gender, Color, Size
from django.contrib.auth.models import User


# Create your models here.

class Cart(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    color = models.CharField(max_length=20,default=None, blank=True, null=True)
    size = models.CharField(max_length=20,default=None, blank=True, null=True)
    image = models.ImageField(upload_to='cartImages', default=None, blank=True, null=True)
    quantity = models.IntegerField(default=1)
    totalprice = models.DecimalField(default=None, blank=True, null=True,max_digits = 20,decimal_places=2)
    def __str__(self) -> str:
        return self.product.name 
    
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    code = models.CharField(default="XXXXXXX", max_length=256)
    state_choices = (
        ('In Queue', 'In Queue'),
        ('Processing', 'Processing'),
        ('Ready', 'Ready'),
        ('Delivered', 'Delivered'),
        ('Paid', 'Paid'),
        ('Cancelled', 'Cancelled'),
    ) 
    state = models.CharField( max_length=256, choices=state_choices, default=state_choices[0][0])
    totalprice = models.IntegerField(default=0)
    quantity = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now=True)
    phonenumber = models.CharField(max_length=20, default=None, blank=True, null=True)
    address = models.CharField(max_length=200, default=None, blank=True, null=True)
    def __str__(self) -> str:
        return 'Order {}'.format(self.id)
    
    def get_total_cost(self):
        return self.totalprice
    
class OrderDetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, blank=True, null=True)
    gender = models.ForeignKey(Gender, on_delete=models.CASCADE, default=None, blank=True, null=True)
    color = models.CharField(max_length=20,default=None, blank=True, null=True)
    size = models.CharField(max_length=20,default=None, blank=True, null=True)
    quantity = models.IntegerField(default=0)
    totalprice = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return '{}'.format(self.id)
    
    def get_cost(self):
        return self.totalprice * self.quantity

register/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) #mối quan hệ một một
    #additional
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)    
    birth_date = models.DateField(help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    site = models.URLField(blank=True) #blank=true có nghĩa là để trống không cần điền vẫn ok
    avatar = models.ImageField(upload_to='images', blank=True) 
    address = models.CharField(max_length=200, default=None, blank=True, null=True)
    phonenumber = models.CharField(max_length=20, default=None, blank=True, null=True)
    def __str__(self) -> str:
        return self.user.username
    

order/views.py
from appProduct.views import product
from django.contrib.auth import SESSION_KEY
from django.http.response import HttpResponse,JsonResponse
from django.shortcuts import render, redirect,get_object_or_404
from .models import Order, OrderDetail, Cart
from appProduct.models import Product, Gender, Color, ImageProduct, Size, Variants
from django.contrib.auth.decorators import login_required,user_passes_test ,permission_required
from django.template.loader import render_to_string, get_template
from django.views.decorators.csrf import csrf_protect
from register.models import  UserProfile
import random



# Create your views here.

# for key, value in request.session.carts.items
#     key: value



carts = {}
def addcart(request):
    if request.is_ajax():
        id_product = request.POST.get('id')
        num = request.POST.get('num')
        productDetail = Product.objects.get(id=id_product)
        if productDetail:
            try:
                variant = Variants.objects.get(product= productDetail)
            except Variants.DoesNotExist:
                variant = None
        else:
            variant = None
        if variant:
            colorlist = variant.color.all()
            sizelist = variant.size.all()
            color = colorlist[0]
            size = sizelist[0]
            colorid = Color.objects.filter(name=color)[0].id
            sizeid = Size.objects.filter(name=size)[0].id
        else:
            color = "None+"
            size = "None+"
            sizeid=1010
            colorid=1010
        if request.user.is_authenticated:       
            if id_product in carts.keys():
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': int(carts[id_product]['num'])+1,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int((int(carts[id_product]['num'])+1) * int(productDetail.price))
                }
            else:
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': num,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(productDetail.price))
                }
        else:
            if str(id_product)+str(colorid)+str(sizeid) in carts.keys():
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': int(carts[str(id_product)+str(colorid)+str(sizeid)]['num'])+1,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int((int(carts[str(id_product)+str(colorid)+str(sizeid)]['num'])+1) * int(productDetail.price))
                }
            else:
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': num,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(productDetail.price))
                }
        if request.user.is_authenticated:
            carts[id_product]= itemCart
        else:
            carts[str(id_product)+str(colorid)+str(sizeid)]=itemCart
        request.session['carts'] = carts
        cartInfo = request.session['carts']
        if request.user.is_authenticated:
            try:
                cartItem = Cart.objects.get(product = productDetail,user = request.user, color = itemCart['color'], size = itemCart['size'])
            except Cart.DoesNotExist:
                cartItem = None
            if cartItem != None:
                cartItem.quantity = int(itemCart['num'])
                cartItem.save()
            else:
                newCartItem = Cart(user = request.user, product = productDetail,quantity = int(itemCart['num']), color = itemCart['color'], size = itemCart['size'], image=itemCart['image'])
                newCartItem.save()
            quantity=0
            totalprice=0
            listCart = Cart.objects.filter(user = request.user)
            for item in listCart:
                quantity += int(item.quantity)
                totalprice += int(item.quantity) * int(item.product.price)
            request.session['quantity']=quantity
            print(totalprice)
        else:
            quantity=0
            totalprice=0
            for key, value in cartInfo.items():
                quantity += int(value['num'])
                totalprice += int(value['num'])*int(float(value['price']))
            request.session['quantity']=quantity
        # html = render_to_string('product/addcart.html',{'carts': cartInfo})
    return JsonResponse({'quantity': quantity, 'quantitproduct': itemCart['num'], 'carts': request.session['carts'], 'totalprice': totalprice})

def addcartdetail(request, product_pk):
    if request.is_ajax():
        id_product = request.POST.get('id')
        num = request.POST.get('num')
        colorid = request.POST.get('color')
        sizeid = request.POST.get('size')
        if colorid:
            color = Color.objects.get(id=colorid)
        else: 
            color = "None+"
            colorid=1010
        if sizeid:
            size = Size.objects.get(id=sizeid)
        else:
            size = "None+"
            sizeid=1010
        if num:
            num=num
        else:
            num=1
        productDetail = Product.objects.get(id=id_product)
        if productDetail:
            try:
                variant = Variants.objects.get(product= productDetail)
            except Variants.DoesNotExist:
                variant = None
        else:
            variant = None
        if request.user.is_authenticated:
            if id_product in carts.keys():
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,   #nếu có hình ảnh thì convert sang string
                    'num': int(carts[id_product]['num']) + int(num),
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(float(productDetail.price)))
                }
            else:
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': num,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(float(productDetail.price)))
                }
        else:
            if str(id_product)+str(colorid)+str(sizeid) in carts.keys():
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,   #nếu có hình ảnh thì convert sang string
                    'num': int(carts[str(id_product)+str(colorid)+str(sizeid)]['num']) + int(num),
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(float(productDetail.price)))
                }
            else:
                itemCart = {
                    'name': productDetail.name,
                    'price': str(productDetail.price),
                    'image': productDetail.image.url,  #nếu có hình ảnh thì convert sang string
                    'num': num,
                    'gender': str(productDetail.gender),
                    'color': str(color),
                    'size': str(size),
                    'totalprice':  int(int(num) * int(float(productDetail.price)))
                }
        if request.user.is_authenticated:
            carts[id_product]= itemCart
        else:
            carts[str(id_product)+str(colorid)+str(sizeid)]=itemCart
        request.session['carts'] = carts
        cartInfo = request.session['carts']
        if request.user.is_authenticated:
            try:
                cartItem = Cart.objects.get(product = productDetail,user = request.user, color = itemCart['color'], size = itemCart['size'])
            except Cart.DoesNotExist:
                cartItem = None
            if cartItem != None:
                cartItem.quantity = int(itemCart['num'])
                cartItem.totalprice = int(itemCart['num'])*productDetail.price
                cartItem.save()
            else:
                newCartItem = Cart(user = request.user, product = productDetail,quantity = int(itemCart['num']), totalprice = int(itemCart['num'])*productDetail.price, color = itemCart['color'], size = itemCart['size']) 
                newCartItem.save()
            quantity=0
            totalprice=0
            listCart = Cart.objects.filter(user = request.user)
            for item in listCart:
                quantity += int(item.quantity)

templates/user/change-password.html
{% extends "base/base.html" %}
{% block block_body_not_nav %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-md">
    <a class="navbar-brand" href="{% url 'home:index' %}">Uniqlo</a>
  </div>
</nav>


<h1 class="text-center mt-5 mb-4 display-3">Change Password</h1>

{% if error %}
  <div class="mb-3 mt-5 w-100 d-flex justify-content-center align-items-center" role="alert" >
    <div class="w-50 alert alert-secondary">{{ error }}</div> 
  </div>
{% endif %}
<form action="" method="POST" class="d-flex flex-column align-items-center">
  {% csrf_token %}
  <div class="mb-3 w-50">
    <label for="id_old_password" class="form-label">Old Password</label>
    <input type="password" name="old_password" required="" id="id_old_password" class="form-control">
  </div>
  <div class="mb-3 w-50">
    <label for="id_new_password1" class="form-label">New Password</label>
    <input type="password" name="new_password1" required="" id="id_new_password1" class="form-control">
  </div>
  <div class="mb-3 w-50">
    <label for="id_new_password2" class="form-label">New password confirmation</label>
    <input type="password" name="new_password2" required="" id="id_new_password2" class="form-control">
  </div>
  <button type="submit" class="btn btn-outline-dark">Change Password</button>
  <a class="mt-3" style="text-decoration: none; color: #212529; font-size: 16px" href="{% url 'appUser:userInfo' %}">Back</a>

</form>
   
{% endblock block_body_not_nav %}

templates/user/editInfo.html
{% extends "base/base.html" %}
{% block block_body_not_nav %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-md">
    <a class="navbar-brand" href="{% url 'home:index' %}">Uniqlo</a>
  </div>
</nav>

<h1 class="text-center mt-5 mb-4 display-3">Edit Info</h1>

{% if error %}
  <div class="alert alert-warning" role="alert">
    <span>{{ error }}</span> 
</div>
{% endif %}
<form enctype="multipart/form-data" method="POST" class="d-flex flex-column align-items-center mb-5">
  {% csrf_token %}
  <div class="mb-3 w-50">
    <label for="id_first_name" class="form-label">First Name</label>
    <input  type="text" name="first_name" maxlength="256" required="" id="id_first_name" class="form-control" value="{{userProfile.first_name}}">
  </div>
  <div class="mb-3 w-50">
    <label for="id_last_name" class="form-label">Last Name</label>
    <input  type="text" name="last_name" maxlength="256" required="" id="id_last_name" class="form-control" value="{{userProfile.last_name}}">
  </div>
  <div class="mb-3 w-50">
    <label for="id_birth_date" class="form-label">Birth Day</label>
    <input type="text" name="birth_date" required="" id="id_birth_date" class="form-control" value="{{userProfile.birth_date|date:'d/m/Y'}}">
  </div>
  <div class="mb-3 w-50">
    <label for="id_site" class="form-label">Url</label>
    <input type="url" name="site" maxlength="200" id="id_site" class="form-control" value="{{userProfile.site}}">
  </div>
  <div class="mb-3 w-50">
    <label for="id_avatar" class="form-label">Default file input example</label>
    <input class="form-control"  type="file" name="avatar" accept="image/*" id="id_avatar">
  </div>
  <button type="submit" class="btn btn-outline-dark mb-5">Register</button>
</form>

{% endblock block_body_not_nav %}

templates/user/order.html
{% extends "base/base.html" %}
{% block block_body %}


<div style="padding-top: 85px;"></div>
<form action="" method="POST">
<table class="table">
    <tr>
        <th>CODE</th>
        <th>TotalPrice</th>
        <th>Quantity</th>
        <th>State</th>
    </tr>
    {% for order in orders %}
    <tr>
        <td>{{order.code}}</td>
        <td>{{order.totalprice}}</td>   
        <td>{{order.quantity}}</td>
        <td>{{order.state}}</td>

    </tr>    
    {% endfor %}
    <tr>
        <td>Toltal</td>
        <td>{{totalprice}}</td>
        <td>{{quantity}}</td>
        <td></td>
    </tr>
</table>
</form>
{% endblock %}

templates/user/userInfo.html
{% extends "base/base.html" %}
{% block block_body %}
{% load static %}
<div style="padding-top: 85px;"></div>

<h3>{{userInfo.user.username}}</h3>
<h3>{{userInfo.first_name}} {{userInfo.last_name}}</h3>
<h3>{{userInfo.birth_date}}</h3>
<h3>{{userInfo.site}}</h3>
{% if userInfo.avatar %}
<img src="{{userInfo.avatar.url}}" alt=""  class="img-thumbnail">
{% endif %}
<a href="{% url 'appUser:editInfo' %}" class="btn btn-primary">Edit Info</a>
<a href="{% url 'change_password' %}" class="btn btn-primary">change password</a>
<a href="{% url 'password_reset' %}"  class="btn btn-primary" >password reset</a>

{% endblock %}